In [1]:
import csv
from decimal import Decimal
import numpy as np
import pandas as pd

## 日積算点灯時間の計算

スケジュール・居室人数別の点灯時間を読み込む  
3人スケジュールについては2人スケジュールと4人スケジュールを按分する

In [2]:
sheets = pd.read_excel('lighting_time_ratio.xlsx', sheet_name=None, index_col=0)
d_w_4 = np.array(sheets['平日4人'].sum())
d_hi_4 = np.array(sheets['休日在宅4人'].sum())
d_ho_4 = np.array(sheets['休日外出4人'].sum())
d_w_2 = np.array(sheets['平日2人'].sum())
d_hi_2 = np.array(sheets['休日在宅2人'].sum())
d_ho_2 = np.array(sheets['休日外出2人'].sum())
d_w_1 = np.array(sheets['平日1人'].sum())
d_hi_1 = np.array(sheets['休日在宅1人'].sum())
d_ho_1 = np.array(sheets['休日外出1人'].sum())

d_w_3 = (d_w_4 + d_w_2) / 2
d_hi_3 = (d_hi_4 + d_hi_2) / 2
d_ho_3 = (d_ho_4 + d_ho_2) / 2

日積算点灯時間の書き出し

In [3]:
d_daily = pd.DataFrame(
    data=[d_w_4, d_hi_4, d_ho_4, d_w_3, d_hi_3, d_ho_3, d_w_2, d_hi_2, d_ho_2, d_w_1, d_hi_1, d_ho_1],
    index=['平日4人', '休日在宅4人', '休日外出4人', '平日3人', '休日在宅3人', '休日外出3人', '平日2人', '休日在宅2人', '休日外出2人', '平日1人', '休日在宅1人', '休日外出1人'],
    columns=['1', '2', '3', '4', '5','6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
).T
d_daily

平日4人  休日在宅4人  休日外出4人   平日3人  休日在宅3人  休日外出3人  平日2人  休日在宅2人  休日外出2人  平日1人  \
1   9.75   10.50    4.75  8.500   9.875   4.375  7.25    9.25    4.00  2.50   
2   2.00    2.25    0.25  2.125   2.125   0.375  2.25    2.00    0.50  0.75   
3   3.25    3.00    0.75  2.750   2.750   0.750  2.25    2.50    0.75  0.25   
4   0.25    0.25    0.00  0.125   0.125   0.000  0.00    0.00    0.00  0.00   
5   0.75    1.25    1.00  1.000   1.125   1.000  1.25    1.00    1.00  0.50   
6   3.50    7.75    1.50  1.750   3.875   0.750  0.00    0.00    0.00  0.00   
7   3.50    7.00    2.25  1.750   3.500   1.125  0.00    0.00    0.00  0.00   
8   2.75    3.25    2.00  2.625   2.750   2.250  2.50    2.25    2.50  0.75   
9   1.75    2.25    1.75  1.375   1.625   1.375  1.00    1.00    1.00  0.25   
10  2.75    2.25    1.75  2.125   1.875   1.625  1.50    1.50    1.50  0.50   
11  2.75    1.50    0.50  2.250   1.125   0.625  1.75    0.75    0.75  0.50   
12  4.25    5.00    3.25  3.375   3.750   3.000  2.50    2.50    2.75  0.75   
13  0.25    0.25    0.00  0.125   0.125   0.000  0.00    0.00    0.00  0.00   
14  1.50    4.25    2.00  1.375   2.625   1.500  1.25    1.00    1.00  0.50   
15  0.75    0.50    0.25  0.375   0.250   0.125  0.00    0.00    0.00  0.00   
16  0.75    0.50    0.25  0.375   0.250   0.125  0.00    0.00    0.00  0.00   
17  1.75    4.25    2.25  1.500   2.625   1.625  1.25    1.00    1.00  0.50   
18  0.50    0.75    0.50  0.625   0.750   0.625  0.75    0.75    0.75  0.25   
19  0.75    0.25    0.25  0.500   0.250   0.250  0.25    0.25    0.25  0.25   

    休日在宅1人  休日外出1人  
1     8.50    2.75  
2     1.75    0.50  
3     1.75    0.75  
4     0.00    0.00  
5     0.75    0.75  
6     0.00    0.00  
7     0.00    0.00  
8     1.50    1.50  
9     0.50    0.50  
10    1.00    1.00  
11    0.75    0.75  
12    1.75    1.75  
13    0.00    0.00  
14    0.75    0.75  
15    0.00    0.00  
16    0.00    0.00  
17    0.75    0.75  
18    0.50    0.50  
19    0.00    0.25

## 年間点灯時間の計算

年間スケジュールの読み込み

In [4]:
vent_schedule = None
with open('schedule.csv', encoding='utf8') as f:
    reader = csv.reader(f, delimiter='\t')
    rows = [row for row in reader]
    vent_schedule = [
        {
            '平日': 'W',
            '休日外': 'HO',
            '休日在': 'HI'
        }[row[4]] for row in rows[1:366]
    ]
vent_schedule = np.array(vent_schedule)
print(vent_schedule)

['HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W'
 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W'
 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W'
 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W'
 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W' 'HI' 'W' 'W' 'W' 'HI'
 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W'
 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W'
 'HI' 'HO' 'W' 'W' 'HO' 'HO' 'HI' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO'
 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W'
 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI'
 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W'
 'W' 'W' 'W' 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'HI' 'W'
 'HI' 'HO' 'W' 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 'W' 'HI' 'HO' 'W'
 'W' 'W' 'W' 'W' 'HI' 'HI' 'W' 'W' 'W' 'W' 

室・居住人数ごとに日積算点灯時間を反映する。

In [5]:
t_i_1_d = np.zeros(shape=(365, 19), dtype=float)
t_i_2_d = np.zeros(shape=(365, 19), dtype=float)
t_i_3_d = np.zeros(shape=(365, 19), dtype=float)
t_i_4_d = np.zeros(shape=(365, 19), dtype=float)

t_i_1_d[vent_schedule=='W', :] = d_w_1
t_i_1_d[vent_schedule=='HI', :] = d_hi_1
t_i_1_d[vent_schedule=='HO', :] = d_ho_1

t_i_2_d[vent_schedule=='W', :] = d_w_2
t_i_2_d[vent_schedule=='HI', :] = d_hi_2
t_i_2_d[vent_schedule=='HO', :] = d_ho_2

t_i_3_d[vent_schedule=='W', :] = d_w_3
t_i_3_d[vent_schedule=='HI', :] = d_hi_3
t_i_3_d[vent_schedule=='HO', :] = d_ho_3

t_i_4_d[vent_schedule=='W', :] = d_w_4
t_i_4_d[vent_schedule=='HI', :] = d_hi_4
t_i_4_d[vent_schedule=='HO', :] = d_ho_4

{
    '1人': t_i_1_d,
    '2人': t_i_2_d,
    '3人': t_i_3_d,
    '4人': t_i_4_d
}

{'1人': array([[8.5 , 1.75, 1.75, ..., 0.75, 0.5 , 0.  ],
        [2.5 , 0.75, 0.25, ..., 0.5 , 0.25, 0.25],
        [2.5 , 0.75, 0.25, ..., 0.5 , 0.25, 0.25],
        ...,
        [2.5 , 0.75, 0.25, ..., 0.5 , 0.25, 0.25],
        [2.75, 0.5 , 0.75, ..., 0.75, 0.5 , 0.25],
        [8.5 , 1.75, 1.75, ..., 0.75, 0.5 , 0.  ]]),
 '2人': array([[9.25, 2.  , 2.5 , ..., 1.  , 0.75, 0.25],
        [7.25, 2.25, 2.25, ..., 1.25, 0.75, 0.25],
        [7.25, 2.25, 2.25, ..., 1.25, 0.75, 0.25],
        ...,
        [7.25, 2.25, 2.25, ..., 1.25, 0.75, 0.25],
        [4.  , 0.5 , 0.75, ..., 1.  , 0.75, 0.25],
        [9.25, 2.  , 2.5 , ..., 1.  , 0.75, 0.25]]),
 '3人': array([[9.875, 2.125, 2.75 , ..., 2.625, 0.75 , 0.25 ],
        [8.5  , 2.125, 2.75 , ..., 1.5  , 0.625, 0.5  ],
        [8.5  , 2.125, 2.75 , ..., 1.5  , 0.625, 0.5  ],
        ...,
        [8.5  , 2.125, 2.75 , ..., 1.5  , 0.625, 0.5  ],
        [4.375, 0.375, 0.75 , ..., 1.625, 0.625, 0.25 ],
        [9.875, 2.125, 2.75 , ..., 2.625, 

月ごとの日にちの始点・終点

In [6]:
d_m = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])
d_end = np.cumsum(d_m)
d_str = np.insert(d_end[0: -1], 0, 0)
d_str, d_end

(array([  0,  31,  59,  90, 120, 151, 181, 212, 243, 273, 304, 334],
       dtype=int32),
 array([ 31,  59,  90, 120, 151, 181, 212, 243, 273, 304, 334, 365],
       dtype=int32))

室ごとに月積算値を計算する

In [7]:
t_i_1_m = np.array([t_i_1_d[d_s:d_e, :].sum(axis=0) for (d_s, d_e) in zip(d_str, d_end)])
t_i_2_m = np.array([t_i_2_d[d_s:d_e, :].sum(axis=0) for (d_s, d_e) in zip(d_str, d_end)])
t_i_3_m = np.array([t_i_3_d[d_s:d_e, :].sum(axis=0) for (d_s, d_e) in zip(d_str, d_end)])
t_i_4_m = np.array([t_i_4_d[d_s:d_e, :].sum(axis=0) for (d_s, d_e) in zip(d_str, d_end)])

In [8]:
t_i_p_m = np.array([[t_i_1_m[:,i], t_i_2_m[:,i], t_i_3_m[:,i], t_i_4_m[:,i]]  for i in range(19)])
t_i_p_m.shape

(19, 4, 12)

## 係数Cの計算

In [9]:
le = np.array([70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0])
ce = np.array([1.0 ,0.5 ,1.0 ,1.0 ,0.8 ,1.0 ,1.0 ,1.0 ,1.0 ,1.0 ,1.0 ,0.5 ,1.0 ,1.0 ,1.0 ,1.0 ,0.5 ,1.0])
f_1 = np.array([232 ,232 ,232 ,232 ,232 ,232 ,232 ,232 ,232 ,177 ,232 ,177 ,232 ,232 ,177 ,177 ,177 ,232])
f_2 = np.array([817 ,817 ,817 ,817 ,817 ,817 ,817 ,817 ,817 ,369 ,817 ,369 ,817 ,817 ,369 ,369 ,369 ,817])
e = np.array([100 ,100 ,100 ,100 ,100 ,100 ,100 ,100 ,50 ,50 ,50 ,50 ,50 ,50 ,50 ,100 ,50 ,50])
a_lz_r = np.array([13.031 ,7.929 ,7.194 ,13.031 ,12.816 ,10.587 ,10.373 ,3.094 ,3.097 ,1.601 ,4.699 ,5.168 ,1.242 ,3.301 ,1.496 ,0.773 ,6.800 ,4.699])
a_ref = np.array([29.81 ,29.81 ,29.81 ,51.34 ,51.34 ,51.34 ,51.34 ,38.93 ,38.93 ,38.93 ,38.93 ,38.93 ,38.93 ,38.93 ,38.93 ,38.93 ,38.93 ,38.93])

In [10]:
c_1_i_p_m = (f_1 / 1.65 * a_lz_r / a_ref * e / 50.0 * ce / le)[:, np.newaxis, np.newaxis] * t_i_p_m[0:18,:,:] * 0.001

In [11]:
c_2_p_m = np.sum((f_2 * e / 50.0 * ce / le)[:, np.newaxis, np.newaxis] * t_i_p_m[0:18, :, :] * 0.001, axis=0) + 12 * t_i_p_m[18] * 0.001


In [12]:
f_prim = 9760.0
alpha_p_m = np.sum(c_1_i_p_m[0:3, :, :], axis=0) * f_prim * 0.001
beta_p_m = np.sum(c_1_i_p_m[3:7, :, :], axis=0) * f_prim * 0.001
gamma_p_m = np.sum(c_1_i_p_m[7:18, :, :], axis=0) * f_prim * 0.001
delta_p_m = c_2_p_m * f_prim * 0.001

In [13]:
alpha_p_m

array([[2.39403574, 2.1244135 , 2.39403574, 2.35262263, 2.40946056,
        2.22266454, 2.6385271 , 2.27179007, 2.35262263, 2.40174815,
        2.4671559 , 2.40174815],
       [4.96517919, 4.4579829 , 4.96517919, 4.72887161, 4.80713409,
        4.77255296, 5.03586161, 4.92983798, 4.72887161, 4.88615664,
        4.84323537, 4.88615664],
       [5.63392265, 5.061989  , 5.63392265, 5.35238291, 5.43642093,
        5.42756676, 5.68105664, 5.61035565, 5.35238291, 5.53517179,
        5.47470076, 5.53517179],
       [6.3026661 , 5.66599509, 6.3026661 , 5.9758942 , 6.06570778,
        6.08258057, 6.32625168, 6.29087331, 5.9758942 , 6.18418694,
        6.10616615, 6.18418694]])

In [14]:
beta_p_m

array([[0.13898592, 0.12528308, 0.13898592, 0.13702837, 0.14290101,
        0.13311327, 0.14290101, 0.13702837, 0.13702837, 0.14094346,
        0.13702837, 0.14094346],
       [0.28580202, 0.25839635, 0.28580202, 0.27405674, 0.28188693,
        0.27797183, 0.28188693, 0.28775957, 0.27405674, 0.28384448,
        0.27405674, 0.28384448],
       [1.34530722, 1.20202195, 1.34530722, 1.2939394 , 1.3167459 ,
        1.27619627, 1.40935479, 1.31328343, 1.2939394 , 1.33102656,
        1.34024384, 1.33102656],
       [2.40481242, 2.14564754, 2.40481242, 2.31382206, 2.35160486,
        2.27442071, 2.53682266, 2.33880729, 2.31382206, 2.37820864,
        2.40643095, 2.37820864]])

In [15]:
gamma_p_m

array([[0.2717588 , 0.24469148, 0.2717588 , 0.27067326, 0.28366415,
        0.25876791, 0.28366415, 0.26580613, 0.27067326, 0.27771148,
        0.27067326, 0.27771148],
       [0.66088452, 0.59762839, 0.66088452, 0.635643  , 0.65516392,
        0.64239083, 0.65310945, 0.66477205, 0.635643  , 0.65802422,
        0.63461576, 0.65802422],
       [0.82579878, 0.7441251 , 0.82579878, 0.79355888, 0.81441279,
        0.7972189 , 0.82986473, 0.8237658 , 0.79355888, 0.82010578,
        0.80128485, 0.82010578],
       [0.99071303, 0.8906218 , 0.99071303, 0.95147476, 0.97366165,
        0.95204696, 1.00662001, 0.98275954, 0.95147476, 0.98218734,
        0.96795394, 0.98218734]])

In [16]:
delta_p_m

array([[ 54.52375897,  48.64623817,  54.52375897,  53.82239143,
         55.58499863,  51.11021291,  58.88687634,  52.34220029,
         53.82239143,  55.0543788 ,  55.47333029,  55.0543788 ],
       [121.51423783, 109.39528766, 121.51423783, 116.08270371,
        118.57527874, 117.3193968 , 121.97981074, 121.28145137,
        116.08270371, 120.04475829, 117.78496971, 120.04475829],
       [172.18348871, 154.64964   , 172.18348871, 164.4019784 ,
        167.45539614, 165.48456806, 174.74640197, 170.90203209,
        164.4019784 , 169.81944243, 168.04748131, 169.81944243],
       [222.8527396 , 199.90399234, 222.8527396 , 212.72125309,
        216.33551354, 213.64973931, 227.5129932 , 220.5226128 ,
        212.72125309, 219.59412657, 218.30999291, 219.59412657]])

In [17]:
with pd.ExcelWriter('lighting_table.xlsx') as writer:
    d_daily.to_excel(writer, sheet_name='table_2')
    pd.DataFrame(
        t_i_1_m,
        index=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        columns=['1', '2', '3', '4', '5','6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
    ).T.to_excel(writer, sheet_name='table_3a')
    pd.DataFrame(
        t_i_2_m,
        index=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        columns=['1', '2', '3', '4', '5','6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
    ).T.to_excel(writer, sheet_name='table_3b')
    pd.DataFrame(
        t_i_3_m,
        index=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        columns=['1', '2', '3', '4', '5','6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
    ).T.to_excel(writer, sheet_name='table_3c')
    pd.DataFrame(
        t_i_4_m,
        index=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        columns=['1', '2', '3', '4', '5','6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
    ).T.to_excel(writer, sheet_name='table_3d')
    pd.DataFrame(
        alpha_p_m.round(3),
        columns=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        index=['1人', '2人', '3人', '4人']
    ).to_excel(writer, sheet_name='table_4')
    pd.DataFrame(
        beta_p_m.round(3),
        columns=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        index=['1人', '2人', '3人', '4人']
    ).to_excel(writer, sheet_name='table_5')
    pd.DataFrame(
        gamma_p_m.round(3),
        columns=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        index=['1人', '2人', '3人', '4人']
    ).to_excel(writer, sheet_name='table_6')
    pd.DataFrame(
        delta_p_m.round(2),
        columns=['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        index=['1人', '2人', '3人', '4人']
    ).to_excel(writer, sheet_name='table_7')
